### ISSUE TITLE
C code in assets/code/lisp is not valid C

### ISSUE THREAD

**Issue by tekknolagi** [tekknolagi/tekknolagi.github.com#13]
Code like

```c
const int kBitsPerByte = 8;                        // bits
const int kWordSize = sizeof(word);                // bytes
const int kBitsPerWord = kWordSize * kBitsPerByte; // bits
```

is not valid C because ` kWordSize * kBitsPerByte` is not a constant expression in C. This works with with Clang because it's more permissive but not in GCC. Investigate & fix.

**Comment by Cadichon** [comment]
Using gcc9 and gcc10 I have been able to compile the code in assets/code/lisp
Can I have more details on how it fails on your end, to try to investigate this problem ? ^^

**Comment by tekknolagi** [comment]
I get errors like

```
$ CC=gcc make
gcc -O0 -g -Wall -Wextra -pedantic -fno-strict-aliasing -std=c99 compiling-integers.c -o bin/compiling-integers
compiling-integers.c:19:26: error: initializer element is not constant
 const int kBitsPerWord = kWordSize * kBitsPerByte; // bits
```

**Comment by tekknolagi** [comment]
Oh, huh. GCC 8 works on my machine but 7.X does not.

**Comment by Cadichon** [comment]
I can still try to fix it under GCC 7 if you wish

**Comment by tekknolagi** [comment]
If you find a palatable way to do that that doesn't involve macros, sure! Otherwise I am pretty ok with requiring GCC8+.

I do wonder why it works in GCC8+, though...

**Comment by Cadichon** [comment]
I don't know it would be an acceptable solution for you, but I think that enum could be used in some places

**Comment by tekknolagi** [comment]
An enum might be good! And I don't like all the text substitution weirdness you have to do with macros. If it's too tricky to do with enums then maybe macros, sure.

**Comment by Cadichon** [comment]
For what I have tried with enums, you can swap every variables that fit into an integer with an enum. You can do it for larger variables, but it generate a warning (-Wpedantic) saying that enum used with larger data aren't standard.

**Comment by tekknolagi** [comment]
Meh, okay, then never mind for now. Thank you for investigating!

**Comment by Cadichon** [comment]
Ok ^^
Good continuation !

**Comment by tekknolagi** [comment]
After some [further discussion](https://twitter.com/thingskatedid/status/1328219150754279424) with @katef on Twitter, I think moving forward with enums is probably the way to go. If you are interested in the patch, go for it, otherwise I will put it up sometime soon.

**Comment by ash-nolan** [comment]
Should be noted that `CC=tcc` produces a similar error:

```sh
~/sources/external/ghuloum[master ?]$ make all CC=tcc CFLAGS='-g'; tcc -v
tcc -g compiling-integers.c -o bin/compiling-integers
compiling-integers.c:19: error: initializer element is not constant
Makefile:24: recipe for target 'bin/compiling-integers' failed
make: *** [bin/compiling-integers] Error 1
tcc version 0.9.27 (x86_64 Linux)
```

I note that source files make use of `_GNU_SOURCE`, so I'm not sure if it's within the scope of the project to support non-gnuc C99 compilers, but it's at least worth a mention.

**Comment by tekknolagi** [comment]
I think that's for MAP_ANONYMOUS or similar. If there's a way around that, great.

**Comment by tekknolagi** [comment]
Fixed compiling-closures.c in 700d53e9d255c2281319ccbeed40513e5afd44b0. Other files are fair game but I am too lazy

**Comment by tekknolagi** [comment]
Others fixed in https://github.com/tekknolagi/ghuloum/commit/492a8132b2b0b9041e51ced3c8de21d01326968f and https://github.com/tekknolagi/ghuloum/commit/49b6fc3e4b40c37d7fdeec1dd8389ac0710b1d28 and https://github.com/tekknolagi/ghuloum/commit/e0ff1d28656b3aa169fca92fa4e200c601846394 so closing this out

**Comment by tekknolagi** [comment]
I can't check on tcc because compiling programs with tcc causes tcc to segfault on my machine...

**Comment by tekknolagi** [comment]
Er, maybe it's linking because `-c` works

**Comment by ash-nolan** [comment]
Can confirm compiles and links on Ubuntu 18.04 with `CC=tcc`:

```
~/sources/external/ghuloum[master]$ make all CC=tcc CFLAGS=''
tcc  mmap-demo.c -o bin/mmap-demo
tcc  compiling-integers.c -o bin/compiling-integers
tcc  compiling-immediates.c -o bin/compiling-immediates
tcc  compiling-unary.c -o bin/compiling-unary
tcc  compiling-binary.c -o bin/compiling-binary
tcc  compiling-reader.c -o bin/compiling-reader
tcc  compiling-let.c -o bin/compiling-let
tcc  compiling-if.c -o bin/compiling-if
tcc  compiling-heap.c -o bin/compiling-heap
tcc  compiling-procedures.c -o bin/compiling-procedures
tcc  compiling-closures.c -o bin/compiling-closures
tcc  compiling-elf.c -o bin/compiling-elf
~/sources/external/ghuloum[master ?]$ tcc -v
tcc version 0.9.27 (x86_64 Linux)
```

**Comment by ash-nolan** [comment]
^^^ On `master` branch w/ commit `3d4f44c3c1030103f70b4723287899adcf57cda2`.
