### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [tekknolagi/tekknolagi.github.com#27]
The domain is missing [GitHub Pages' AAAA records](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) for IPv6 support, which are:
```
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153 
```

**Comment by tekknolagi** [comment]
Hi @tambry -- fixed. Let me know if it works for you and I'll close. Thanks.

**Comment by tambry** [comment]
Working, thanks! 👍
