### ISSUE TITLE
Tried Zig for compiling C?

### ISSUE THREAD

**Issue by impredicative** [tekknolagi/tekknolagi.github.com#45]
Regarding the post https://bernsteinbear.com//blog/compiling-ml-models/ , I'm curious how the Zig compiler of C code will contrast with Clang and TCC.

**Comment by tekknolagi** [comment]
IIRC Zig uses Clang under the hood to compile both Zig and C, but they
are moving to a Zig-only compiler for Zig (not C). So we will probably
see the same results
