### ISSUE TITLE
BPython is this for people who would prefer to just use a superset that's maintained.

### ISSUE THREAD

**Issue by Eirikur** [tekknolagi/tekknolagi.github.com#54]
Hi, this is an excellent post. If I was aware that you could harness the REPL, I certainly didn't recall it.
I started thinking of how I'd customize your code from your article and ran into the fact
that for all the use cases that I can think of, I'd just use the BPython REPL, which is really, really, nice.
It seems you can even embed BPython in a program:
https://snyk.io/advisor/python/bpython/functions/bpython.embed

I think it's worth you adding a line or two to talk about when your technique would be the best thing,
and mentioning both BPython and IPython as ready-to-go alternatives for situations where that
would work. I use BPython for quickly trying things all the time.

My best,
Eirikur

**Comment by tekknolagi** [comment]
Thanks for the feedback. The point is more to show all the batteries that are already included, and it seems as though bpython is an external package.

**Comment by tekknolagi** [comment]
Did you come across the post from a newsletter or something? I seem to have gotten a bunch of traffic from a mysterious email source.
